* fooAuth
We don't care about oAuth.

** About
fooAuth is a Rails app (running on [[http://www.sinatrarb.com/][Sinatra]]) that will convert your
basic auth requests (using username + password) to oAuth request (with
all the tokens, keys and secrets...).

** Status
fooAuth is still in development phase (actually even still in design
phase). Currently I am able to post a tweet on Twitter using fooAuth.

** Usage

Pass the following parameters to you fooAuth requests:
- foo_site: the API site you are using (e.g. 'http://api.twitter.com')
- foo_page: the API page you want to send to request to (e.g. '/statuses/update.json')
- foo_consumer_key & foo_consumer_secret: oAuth consumer key and
  secret acquired from API you are using (for twitter use:
  http://dev.twitter.com/apps/new)
- foo_username:
- foo_password:
Any other parameter will be passed to the 'foo_page' request.

*** Example
test.sh included in the project will make it possible for you to post
a tweet.
Usage: ./test.sh username password 'Tweet message'


